# AUTOGENERATED! DO NOT EDIT! File to edit: 02-data-augmentation-and-deployment.ipynb.

# %% auto 0
__all__ = ['learn', 'categories', 'examples', 'intf', 'classify_image']

# %% 02-data-augmentation-and-deployment.ipynb 18
from fastai.vision.all import *
import gradio as gr

# %% 02-data-augmentation-and-deployment.ipynb 19
learn = load_learner('bears.pkl')

# %% 02-data-augmentation-and-deployment.ipynb 20
categories = ('grizzly','black','teddy')

def classify_image(img):
    pred, idx, probs = learn.predict(img)
    return dict(zip(categories, map(float, probs)))  # need to map tensor to float for gradio 

# %% 02-data-augmentation-and-deployment.ipynb 21
examples = ["black.jpg", "grizzly.jpg", "teddy.jpg"]

intf = gr.Interface(fn=classify_image, inputs="image", outputs="label", examples=examples)
intf.launch(inline=False)

